### ISSUE TITLE
Patch for 10.10.3

### ISSUE THREAD

**Issue by ghost** [vinc3m1/mac-pixel-clock-patch#11]
I tried manually patching the binary for 10.10.3, but I am not well versed in assembly. Is there a working patch for 10.10.3 or plans to update this one?

**Comment by ghost** [comment]
I actually got around this problem by uninstalling SwichResX, resetting nvram and using an active miniDP to HDMI converter. Patch is no longer needed.

**Comment by Floris497** [comment]
look at my fork
